export enum PokemonType {
	NORMAL = 'Normal',
	FIRE = 'Fire',
	WATER = 'Water',
	GRASS = 'Grass',
	ELECTRIC = 'Electric',
	ICE = 'Ice',
	FIGHTING = 'Fighting',
	POISON = 'Poison',
	GROUND = 'Ground',
	FLYING = 'Flying',
	PSYCHIC = 'Psychic',
	BUG = 'Bug',
	ROCK = 'Rock',
	GHOST = 'Ghost',
	DRAGON = 'Dragon',
	STEEL = 'Steel',
	DARK = 'Dark',
	FAIRY = 'Fairy',
}
